### PR TITLE
Enrich Jest type with all CLI options

### PR DESCRIPTION
**Pull request by erikengervall**
#100

### CODE REVIEW

**Comment by n1ru4l** [comment]
Isn't it possible to import the CLI interface/type from jest?

**Comment by erikengervall** [comment]
> Isn't it possible to import the CLI interface/type from jest?

Couldn't find a way to extract it 🙁

**Comment by n1ru4l** [comment]
https://www.npmjs.com/package/@jest/types ?

**Comment by erikengervall** [comment]
> https://www.npmjs.com/package/@jest/types ?

Christ, not sure how I managed to miss this. I'll look into it 😅 

thanks buddy 👍

**Comment by erikengervall** [comment]
> https://www.npmjs.com/package/@jest/types ?

Looked into this quickly yesterday and doesn't look like they've got types for calling `runCLI` programmatically [(it's combined with the other configuration and wrapped with a type from `yargs`)](https://github.com/facebook/jest/blob/master/packages/jest-types/src/Config.ts#L426). I'll probably go ahead with this change for now as it resembles their documentation and later open a PR towards Jest to expose the pure CLI types since they've actually got the capabilities for it.

Here's an [issue](https://github.com/facebook/jest/issues/5048) regarding the topic that gives a bit of insight.

**Pull request merged**
