### PR TITLE
Add configurable readiness retry count

### PR DESCRIPTION
**Pull request by rupurt**

### CODE REVIEW

**Review by erikengervall — APPROVED** [review]

**Comment by erikengervall** [comment]
Hey @rupurt, thanks for your contribution! 👍

**Comment by erikengervall** [comment]
Before including this in a new release I'd like it included in the docs.

I'm in the middle of simplifying the docs so I could do that change myself 🙂  Created an [issue](https://github.com/erikengervall/dockest/issues/201) to keep track of it.

**Comment by erikengervall** [comment]
Available in `next` release `2.1.0-a2198f7`: https://www.npmjs.com/package/dockest/v/2.1.0-a2198f7

**Comment by rupurt** [comment]
@erikengervall sweet! Thanks for the quick merge and release.

**Pull request merged**
