### PR TITLE
Proposal : Overhaul readiness checks

### PR DESCRIPTION
**Pull request by n1ru4l**
This is a breaking change the overhauls the existing readiness check system. All readiness check related stuff is now exported via `"dockest/readiness-check"`.

By default a readiness check does no longer have a retry. Retry must be explicitly declared by wrapping a readiness check with the `withRetry` function exported from `"dockest/readiness-check"`.

```ts
import { withRetry } from "dockest/readiness-check";
const readinessCheck = async () => {
  throw new Error("Will always fail.")
}

const readinessCheckWithRetry = withRetry(readinessCheck, 10);
```

Having a global retry does make sense for brute-force attempts (e.g. try run command 10 times before failing), but not for readiness checks that observe the docker event stream or potentially in the future logs.

The old readiness checks for redis, postgres, and web are now also exported from that namespace. Those already have the retry "trait" applied. So it is a bit easier to upgrade, if anyone is already relying on that readinesschecks.

```ts
import {
  createWebReadinessCheck,
  createRedisReadinessCheck,
  createPostgresReadinessCheck,
} from "dockest/readiness-check"
```

The `zeroExitCodeReadinessCheck` assumes that a container is ready when it exits with the exit code `"0"`. This is useful if you have a container that is responsible for running database migrations.

The `containerIsHealthyReadinessCheck` assumes that a container is ready once the docker health check pubishes a "heathy" value via the docker event stream. This is IMHO a better and universal way of verifying that a container is ready (in comparison to the old redis, postgres, and web retry-readiness checks), as many containers already come with a health-check definition in their Dockerfile. Most setups should therefore be best off by using that readiness check.

The `withNoStop` utility can be used to automatically fail any user-land readiness check in case the container exists preliminary. It is also used by the `containerIsHealthyReadinessCheck`, `createWebReadinessCheck`, `createRedisReadinessCheck` and `createPostgresReadinessCheck` for faster feedback (instead of waiting for a retry to time out).

### CODE REVIEW

**Review by erikengervall — APPROVED** [review]

**Comment by erikengervall** [comment]
Finally had a chance to review this - looks good @n1ru4l 👍

**Comment by erikengervall** [comment]
Let's get this and https://github.com/erikengervall/dockest/pull/213 into a new major

**Comment by n1ru4l** [comment]
we are also already using these changes successfully in our ci pipelines on our private fork :)

**Comment by erikengervall** [comment]
> we are also already using these changes successfully in our ci pipelines on our private fork :)

haha, happy to hear it's been pre-beta tested 😄

**Comment by erikengervall** [comment]
@n1ru4l do you have permission to merge PRs once approved?

**Comment by n1ru4l** [comment]
@erikengervall nope 😅

**Comment by erikengervall** [comment]
> @erikengervall nope 😅

alright, gimmie a minute to dig around in settings haha

**Comment by erikengervall** [comment]
@n1ru4l so i've set a requirement for 1 review on protected branches, which is only only `master` currently

i saw u accepted my invite to become a collaborator, i hope this enables the shiny merge button 🤞

**Comment by n1ru4l** [comment]
awesome :)

**Pull request merged**
