### PR TITLE
feat: use docker-compose cli for merging compose files

### PR DESCRIPTION
**Pull request by n1ru4l**
addresses the concerns mentioned in https://github.com/erikengervall/dockest/pull/81#issuecomment-533440356
> Hey, @erikengervall I don't know the exact details of how docker-compose merges multiple config files, but I have some concerns that the deepMerge you are using could behave differently.
Therefore I would suggest using the docker-compose cli for merging those:
docker-compose -f docker-compose.yml -f docker-compose.local.yml config

### CODE REVIEW

**Comment by erikengervall** [comment]
Moving [this](https://github.com/erikengervall/dockest/pull/81#issuecomment-533455819) conversation here. The link refers to a comment to a description of compose merge behaviour which might be interesting.

I'm interested in what the full initialization flow would look like. Is it something like this?
1. compose merge local files into X
2. convert X to object representation Y
3. merge attachedRunners with Y
4. generate compose file Z
5. run Z

Or would you skip step 3 in case of existance of `composeFile` configuration and have `attachedRunners` then only work as a responsivenessCheck configuration.

I guess the main question here is whether one would allow users to provide _both_ compose files and attach runners 🤔

**Comment by n1ru4l** [comment]
> I guess the main question here is whether one would allow users to provide both compose files and attach runners 🤔

As already mentioned in https://github.com/erikengervall/dockest/pull/78:

> I personally would prefer the approach of not automatically guessing the container type.
I also would still prefer having to declare a runner for each container that I want to run because I might not want to spin up all containers that are referenced in the compose file at once.

By default, when one or more `docker-compose.yml` file is referenced their configuration is automatically merged with the one provided by a `Runner` that has the same `service` - name.

I would also make it mandatory having to declare the Runners for your containers (even with a compose file). It might feel like having to write some boilerplate code, but I think the process of doing so gives the user a more clear understanding of what he is doing. I also prefer declarative over magic approaches. No Runner defined for a service = no container for that service will be started.

**Example:**
- docker-compose.yml
- docker-compose.overrides.yml
- dockest.ts runner definition

1. convert runner configuration to yml (e.g. `docker-compose.runner.yml`)
2. merge `docker-compose.yml`, `docker-compose.overrides.yml`, `docker-compose.runner.yml`
3. Pick services that are referenced via a runner
4. validate those (image? build?)
5. `docker-compose up` but only for the services that are referenced by a runner (in  case there is a `dependsOn` it should if there is no runner defined for those containers)

**Comment by n1ru4l** [comment]
@erikengervall I adjusted the merge flow according to my comment (https://github.com/erikengervall/dockest/pull/82#issuecomment-533468530) (71c995f) and added an option for automatically enabling container configuration guessing (d21b729). Furthermore, I altered the `docker-compose` command to only start services that have a runner declared (61ab7d8)

**Comment by n1ru4l** [comment]
@erikengervall I noticed that the output format of the `ports` configuration fo the `docker-compose` cli differs between compose file version `3.0` and `3.7`:

```snapshot
 Object {
        "services": Object {
          "composeRedis": Object {
            "image": "im:a:duplicate",
            "ports": Array [
    -         "6378:6379/tcp",
    +         Object {
    +           "published": 6378,
    +           "target": 6379,
    +         },
            ],
          },
        },
    -   "version": "3.0",
    +   "version": "3.7",
      }
```

How should this be handled? Use different logic for accessing the port mappings based on the `compose-file` version? Or only support the latest compose-file version syntax (as it seems to be backward compatible in the 3.x range).

Related commits: https://github.com/erikengervall/dockest/pull/82/commits/593b582bda7c351fbd8fc3108adf411ccc92d835

**Comment by n1ru4l** [comment]
Also, I am thinking about whether a runner config validation is even necessary. The docker-compose CLI already validates the config a first time when merging the single files and even a second time when running the up command. Why should we reimplement the logic of docker-compose?

The only benefit I see right now are the following:

- Smarter error messages.
- Responsiveness Command validation

The latter would be outsourced with an API similar to https://github.com/erikengervall/dockest/pull/78#issuecomment-533323324

**Comment by erikengervall** [comment]
> **Only support the latest compose-file version syntax.**

I'd prefer this approach since it also encourages people to keep up with compose versions.

**Comment by erikengervall** [comment]
> Also, I am thinking about whether a runner config validation is even necessary. The docker-compose CLI already validates the config a first time when merging the single files and even a second time when running the up command. Why should we reimplement the logic of docker-compose?
> 
> The only benefit I see right now are the following:
> 
> * Smarter error messages.
> * Responsiveness Command dependency validation (port/credentials)
> 
> The latter would be moved outside the runner with an API similar to [#78 (comment)](https://github.com/erikengervall/dockest/pull/78#issuecomment-533323324)

Yes, the error messages are a large portion of it. If we're able to preserve meaningful errors that'd be great!

**Comment by n1ru4l** [comment]
@erikengervall Okay, I think I got everything covered. The changes got bigger than I expected 😕

I tried to add ad detailed message with references to comments/threads, I hope that can help you while reviewing!

**Comment by erikengervall** [comment]
Running your branch locally I found that one of the examples, `examples/integration`, fails and doesn't cause a failure in the CI: `(node:6054) UnhandledPromiseRejectionWarning: Error: 💥 Could not resolve required environment variable ZOOKEEPER_CLIENT_PORT. Expected 2181 to appear as value in ports object`

Furthermore, there seem to be a discrepancy between running lint via yarn `yarn lint` and via command line directly `yarn eslint ./src/**/*.ts`. The latter causes errors.

Obviously these are misconfigurations introduced prior to this PR, and you don't have to solve the configuration for this PR but make sure that `eslint` and `examples/integration` runs smoothly locally.

If you might know what the misconfiguration might be, feel free to include it in this PR. If not I'll try to spend some time on it next week when I'm back from vacations.

**Comment by n1ru4l** [comment]
> Furthermore, there seem to be a discrepancy between running lint via yarn yarn lint and via command line directly yarn eslint ./src/**/*.ts. The latter causes errors.

[Source:](https://eslint.org/docs/user-guide/command-line-interface)
> Please note that when passing a glob as a parameter, it will be expanded by your shell. The results of the expansion can vary depending on your shell, and its configuration. If you want to use node glob syntax, you have to quote your parameter (using double quotes if you need it to run in Windows), as follows:

I will change it to `eslint "./src/**/*.ts"` in a separate PR.

**Pull request merged**
